title: AnimatedLEDStrip
description: 
google_analytics: 
show_downloads: false
theme: minimal-mistakes-jekyll

gems:
  - jekyll-mentions
  - minimal-mistakes-jekyll

github:
  repository_url: https://github.com/AnimatedLEDStrip
